Repository chromaui/storybook-addon-pseudo-states, pull requests merged in 2024-03, with the labels that each got.

#104 Exclude ::-webkit-slider-thumb pseudo-element from rewrites
  src/constants.ts
Labels: patch, skip-release

#106 Fix CI config
  .github/workflows/check-labels.yml
  .github/workflows/chromatic.yml
  .github/workflows/release.yml
  chromatic.config.json
  package.json
  yarn.lock
Labels: patch, release

#105 Avoid generating invalid selector with `:has`
  src/preview/rewriteStyleSheet.test.ts
  src/preview/rewriteStyleSheet.ts
Labels: patch, release

#107 Use bundling strategy suitable for Storybook 8
  .babelrc.js
  .storybook/preview.js
  package.json
  tsup.config.ts
  yarn.lock
Labels: patch, release

#100 Upgrade to Storybook 8
  .babelrc.js
  .nvmrc
  .storybook/main.js
  .storybook/preview.js
  chromatic.config.json
  package.json
  src/index.ts
  src/manager/PseudoStateTool.tsx
  tsconfig.json
  tsup.config.ts
  yarn.lock
Labels: major, release

#109 Add `author` and `publishConfig` to package.json
  package.json
Labels: patch, release

#112 switch off older Icons reference #111
  src/manager/PseudoStateTool.tsx
Labels: patch, release
